apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
      - name: go-server
        image: phmelomorais/code-education-go-webserver
        resources:
          limits:
            memory: "128Mi"
        ports:
        - containerPort: 8000
